#lang racket/base
(require "lib.rkt" simple-python-api)

(define-moviepy
  "videoclip"
  ((read-videoclip (_pyunicode) () PyObj*)
   (get-height (PyObj*) () _pyssize)
   (get-width (PyObj*) () _pyssize)
   (get-frames-num (PyObj*) () _pyssize)
   (resize-videoclip (PyObj* _pydouble) () PyObj*)
   (rotate-videoclip (PyObj* _pydouble) () PyObj*)
   (extract-subregion (PyObj* (pylist _pyssize _pyssize) (pylist _pyssize _pyssize))
                      ()
                      PyObj*)
   (append-videoclips (pylistof PyObj*)
                      ()
                      PyObj*)
   (mirror-x (PyObj*)
             ()
             PyObj*)
   (mirror-y (PyObj*)
             ()
             PyObj*)
   (map-frames (PyObj* PyObj*)
               ()
               PyObj*)
   (save-frame (PyObj* _pyunicode _pydouble)
               ()
               _pyvoid)
   (write-videoclip (PyObj* _pyunicode)
                    ()
                    _pyvoid)
   (write-videoclip-to-gif
    (PyObj* _pyunicode)
    ()
    _pyvoid)
   (write-videoclip-to-images
    (PyObj* _pyunicode)
    ()
    _pyvoid))
  ())
